import type { Config } from "tailwindcss";
import containerQueries from '@tailwindcss/container-queries';
import forms from '@tailwindcss/forms';

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        rose: "rgb(var(--theme-color-rgb) / <alpha-value>)",
        champagne: "#F5E6CA",
        sage: "#7D9E8C",
        cream: "#FAFAF8",
        
        // Stitch Design System Colors
        "surface-dim": "#e1d8d7",
        "on-error": "#ffffff",
        "surface-container-highest": "#e9e0e0",
        "surface-container-lowest": "#ffffff",
        "primary": "#7b5455",
        "on-secondary-fixed": "#0f1f0f",
        "on-primary-fixed": "#2f1314",
        "on-tertiary-fixed-variant": "#2e4a5d",
        "tertiary-fixed-dim": "#adcae2",
        "surface-tint": "#7b5455",
        "inverse-surface": "#342f2f",
        "outline": "#827473",
        "tertiary-container": "#b5d2ea",
        "primary-fixed": "#ffdad9",
        "on-primary-container": "#734e4e",
        "on-secondary-container": "#556852",
        "on-primary": "#ffffff",
        "secondary": "#51634e",
        "secondary-fixed-dim": "#b8ccb3",
        "secondary-fixed": "#d3e8ce",
        "surface-bright": "#fff8f7",
        "primary-container": "#f4c2c2",
        "on-primary-fixed-variant": "#613d3e",
        "on-error-container": "#93000a",
        "surface-variant": "#e9e0e0",
        "outline-variant": "#d4c2c2",
        "background": "#fff8f7",
        "surface-container-low": "#fbf1f1",
        "surface": "#fff8f7",
        "surface-container": "#f5eceb",
        "on-surface-variant": "#504444",
        "surface-container-high": "#efe6e5",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#394b38",
        "secondary-container": "#d1e6cb",
        "on-tertiary": "#ffffff",
        "tertiary": "#466276",
        "primary-fixed-dim": "#ecbaba",
        "inverse-on-surface": "#f8efee",
        "on-tertiary-fixed": "#001e2f",
        "tertiary-fixed": "#c9e6fe",
        "inverse-primary": "#ecbaba",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#3f5b6f",
        "on-surface": "#1f1b1b",
        "on-background": "#1f1b1b",
        foreground: "var(--foreground)",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "container-max": "1280px",
        "stack-md": "16px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "stack-xl": "64px",
        "stack-lg": "32px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        heading: ["var(--font-cormorant)", "serif"],
        body: ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", {"lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "headline-lg": ["40px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "display-lg-mobile": ["40px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.08em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [containerQueries, forms],
};
export default config;
